"""Generate the boot-splash: aperture-shutter mark on white, pre-rotated 180
(display is mounted inverted), emitted as LVGL RGB565 C arrays in the exact
format of scripts/avatar_convert/convert_avatars.py."""
import math
import sys
from pathlib import Path

from PIL import Image, ImageDraw

OUT_DIR = Path(r"C:\Users\domin\tools\stackchan-mcp\firmware\main\boards\stackchan")
PNG_PREVIEW = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("splash_preview.png")
W, H = 160, 120
SS = 4  # supersample

BLUE = (0, 140, 210)

def draw_aperture(img: Image.Image, cx, cy, ro, ri, channel_w, color):
    # Authentic iris construction: a solid disc CUT by 8 thin chords, each
    # tangent to the inner circle — the blades are what remains between the
    # cuts, and the centre becomes the natural octagon opening.
    d = ImageDraw.Draw(img)
    d.ellipse([cx - ro, cy - ro, cx + ro, cy + ro], fill=color)
    L = math.sqrt(ro * ro - ri * ri) * 1.02
    for k in range(8):
        th = math.radians(k * 45.0)
        tx, ty = cx + ri * math.cos(th), cy + ri * math.sin(th)
        dx, dy = -math.sin(th), math.cos(th)
        d.line([(tx, ty), (tx + dx * L, ty + dy * L)],
               fill=(255, 255, 255), width=channel_w)
    return img

img = Image.new("RGB", (W * SS, H * SS), (255, 255, 255))
cx, cy = W * SS / 2, H * SS / 2
ro = int(H * SS * 0.40)   # outer radius ~48px at 120 high
ri = int(ro * 0.30)
img = draw_aperture(img, cx, cy, ro, ri, channel_w=int(ro * 0.11), color=BLUE)

img = img.resize((W, H), Image.LANCZOS)
img = img.rotate(180)  # display is mounted inverted
img.save(PNG_PREVIEW)
print(f"preview: {PNG_PREVIEW}")

if "--emit" in sys.argv:
    # pack little-endian RGB565 (mirrors convert_avatars.py)
    px = img.tobytes()
    data = bytearray(len(px) // 3 * 2)
    j = 0
    for i in range(0, len(px), 3):
        r, g, b = px[i], px[i + 1], px[i + 2]
        v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
        data[j] = v & 0xFF
        data[j + 1] = (v >> 8) & 0xFF
        j += 2

    lines = []
    lines.append("// GENERATED by gen_splash.py — aperture boot splash, 180-rotated")
    lines.append("// for the inverted display mount. Do not edit by hand.")
    lines.append('#include "boot_splash.local.h"')
    lines.append("")
    lines.append(f"static const uint8_t boot_splash_map[{len(data)}] = {{")
    for off in range(0, len(data), 16):
        chunk = ", ".join(f"0x{b:02X}" for b in data[off:off + 16])
        lines.append(f"    {chunk},")
    lines.append("};")
    lines.append("")
    lines.append("const lv_image_dsc_t boot_splash_img = {")
    lines.append("    .header = {")
    lines.append("        .magic = LV_IMAGE_HEADER_MAGIC,")
    lines.append("        .cf = LV_COLOR_FORMAT_RGB565,")
    lines.append("        .flags = 0,")
    lines.append(f"        .w = {W},")
    lines.append(f"        .h = {H},")
    lines.append(f"        .stride = {W * 2},")
    lines.append("        .reserved_2 = 0,")
    lines.append("    },")
    lines.append(f"    .data_size = {len(data)},")
    lines.append("    .data = boot_splash_map,")
    lines.append("};")
    lines.append("")
    (OUT_DIR / "boot_splash.local.cc").write_text("\n".join(lines), encoding="utf-8")
    (OUT_DIR / "boot_splash.local.h").write_text(
        "\n".join([
            "// GENERATED by gen_splash.py — see boot_splash.local.cc",
            "#pragma once",
            '#include "lvgl.h"',
            "",
            "#ifdef __cplusplus",
            'extern "C" {',
            "#endif",
            "extern const lv_image_dsc_t boot_splash_img;",
            "#ifdef __cplusplus",
            "}",
            "#endif",
            "",
        ]),
        encoding="utf-8",
    )
    print(f"emitted: {OUT_DIR}\\boot_splash.local.{{cc,h}} ({len(data)} bytes)")
